### ISSUE TITLE
MediaSource Controller not work well

### ISSUE THREAD

**Issue by yoshi315** [xjsframework/xjs#103]
Hello,

Many thanks to your works. It's great.

I've a problem when i wanna to schedule a list of mp4 file to play by XJS Framework and Extension.
When i changed the file from one to another, i used the 'MediaSource.setValue' and 'MediaSource.setPlaybackPosition' API methods.

```
//get the source frome the scene

source.setValue(new_path)
.then(function(source) {
    return source.setPlaybackPosition(0.0)
})
.then(function(source) {
    return source.setPlaying(true);
})
.then(function(source) {
    return source.getPlaybackPosition();
})
.then(function(pos) {
    showVal("get [" + new_path + "] at pos = " + pos);
});
```

The 'setValue' worked fine, but 'setPlaybackPosition' was not working correctly.

I think the reason is not the API's fault, but the process when the API call MP4 play lib.
The MP4 player lib may be returned immediately when the player is OPENING not OPENED.
So, the player is not response to 'setPlaybackPosition' correctly.

Base on this idea, i've tried another little test.
```
source.setValue(new_path);
setTimeout(function () {
    source.setPlaybackPosition(0.0)
}, 3000);
```
It works.

Another question is that do you any suggestion about what format(RMVB, AVI) of video can i use to keep away from the wired situation above.

Thank u.

**Comment by dcefram** [comment]
Hi, I tried doing the same thing, and it does seem to work without the `setTimeout`... Just to rule out that this has something to do with the XSplit version that you are using... Do you mind telling us what XSplit Broadcaster are you on? Also, if possible, can you try your plugin using the latest 1.4.0 XJS release along with the latest 2.8 version of XSplit Broadcaster (in case you're not yet on that version).

The code that I'm using is just the same as yours:

```javascript
new_val = "C:\\Path\\to\\the\\video\\file.mp4";

xjs.Scene.getActiveScene().then(function(scene) {
  return scene.getItems();
}).then(function(items) {
  // Assuming that we have only one item in the current scene, which is a media item :)
  return items[0].setValue(new_val)
}).then(function(item) {
    return item.setPlaybackPosition(0.0)
})
.then(function(item) {
    return item.setPlaying(true);
})
.then(function(item) {
    return item.getPlaybackPosition();
})
.then(function(pos) {
    console.log("get [" + new_val + "] at pos = " + pos);
});
```

If you're using the latest XSplit Broadcaster and XJS Framework, then we would also like to get an idea of the mp4 filesize and duration just so that we can replicate your issue on our end :)

**Comment by yoshi315** [comment]
Hi @dcefram 
Thank u for your reply.
My XBC version is the newest version (2.8 1605.3127)
My xjs-framework is 1.3.

Under your advice, I've update xjs-framework to 1.4
The setValue and setPlaybackPosition issue is solved.

Furthermore,
I've found another issue.

```javascript
source.setValue(path)
.then(function(source) {
	return source.setPlaybackPosition(plus_seconds);  //work fine
})
.then(function(source) {
	return source.setPlaying(true);  //work fine
})
.then(function(source) {
	return source.isPlaying();  //work fine
})
.then(function(flag) {
	showVal("playerChange: changed and isPlaying = " + flag);  //not good
});
```

When I played a list of mp4 file(about 300m~500m), the output is
```
playerChange: changed and isPlaying = false
playerChange: changed and isPlaying = true
playerChange: changed and isPlaying = false
playerChange: changed and isPlaying = true
...
```

That is so wired. Thank you.

**Comment by dcefram** [comment]
That's weird. Your mp4 files' duration is around 300m~500m ('m' as in minutes or MB?)? I tried it out on a list of mp4 files (around 4mins long each) and added a setInterval set to 5000ms to change the video file every 5 seconds... and it works on my end.

Here's my code (in ES2015 syntax):

```javascript
  const output = document.getElementById('output');
  const DIR_PATH = 'C:\\Users\\default\\Videos\\MV\\';
  const videos = [
    'DATI - OFFICIAL MUSIC VIDEO.mp4',
    'Counting Stars - OneRepublic (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover).mp4',
    'Just Give Me a Reason (P!nk ft. Nate Ruess) - Sam Tsui, Kylee, & Kurt Schneider Cover.mp4',
    'Heart Attack - Demi Lovato (Sam Tsui & Chrissy Costanza of ATC).mp4'
  ];
  let idx = 0;

  // Expose to window so that we can execute the tester functions in remotedebugger if needed
  window.tester = () => {
    xjs.Scene.getActiveScene()
      .then(scene => scene.getItems())
      .then(items => items.find(item => item instanceof xjs.MediaItem))
      .then(item => item.setValue(`${DIR_PATH}${videos[idx]}`))
      .then(item => item.setPlaybackPosition(0.0))
      .then(item => item.setPlaying(true))
      .then(item => item.isPlaying())
      .then(flag => {
        const p = document.createElement('p');
        p.textContent = `playerChange(file=${videos[idx]}): isPlaying = ${flag}`;
        output.appendChild(p);
        idx++;
      });
  };

  const handler = setInterval(window.tester, 5000);

  window.stopTester = () => {
    clearInterval(handler);
  };
```

the output is as follows:
```
playerChange(file=DATI - OFFICIAL MUSIC VIDEO.mp4): isPlaying = true
playerChange(file=Counting Stars - OneRepublic (Alex Goot, Kurt Schneider, and Chrissy Costanza Cover).mp4): isPlaying = true
playerChange(file=Just Give Me a Reason (P!nk ft. Nate Ruess) - Sam Tsui, Kylee, & Kurt Schneider Cover.mp4): isPlaying = true
playerChange(file=Heart Attack - Demi Lovato (Sam Tsui & Chrissy Costanza of ATC).mp4): isPlaying = true
```

So with that said, I would like to know what does the 'm' stand for on your sentence:
> When I played a list of mp4 file(about 300m~500m), the output is

And what's the duration of your timer before it sets a new value using `setValue`?

**Comment by yoshi315** [comment]
Hello,
I mean 'MB'

**Comment by dcefram** [comment]
Hi, I re-tested it using 900MB ~ 1.6GB videos, and it still worked as expected. Can you try it out on your end? Here's the Gist: https://gist.github.com/dcefram/24d9fd0f34ba85a5c818cab7e27fa293#file-main-es5-js

Just replace the `DIR_PATH` to the path of your videos, and add the video file names to `videos` array. Also make sure that you have a div with an ID as `output` on your HTML file :)

**Comment by yoshi315** [comment]
Hello,thanks for reply.

I noticed a detail:
**1.I changed the MediaItem's Value in Scene1,but the Scene1 was not the active scene. So the isPlaying property's value is FALSE.(Sorry for wasting your time.)**
2.And then I made Scene1 to the active scene.

Besides, I don't known what the best practice of:
1.changing the MediaItem's Value in the first step
2.changing the scene in the second step
3.the MediaItem is goint to play automaticlly

My early code is below:
```javascript
function xjsRun(callback)
{
  XJS.ready()
  .then(function() {
    return Scene.getById(1);
  })
  .then(function(scene) {
    return scene.getItems();
  })
  .then(function(items) {
    for (var item in items) {

      var p_item = Promise.resolve(item);
      var p_type = items[item].getType();

      Promise.all([p_item, p_type]).then(function(rets) {
        var ret_item = rets[0];
        var ret_type = rets[1];
        var source   = items[ret_item];

        if (ret_type === ItemTypes.FILE)
        {
          if (source instanceof MediaItem)
          {
            callback.call(this, source);
          }
          else
          {
            showVal("source is not a instance of MediaItem");
          }
        }
      })
    }
  });
}
  
function changeScene(index)
{
  let scene_index = parseInt(index);

  XJS.ready()
  .then(function() {
    showVal("scene is changing to [" + scene_index + "]");
    return Scene.setActiveScene(scene_index);
  })
  .then(function(ret_set_active_scene) {
    if (ret_set_active_scene)
    {
      showVal("scene is changed to [" + scene_index + "]");
      last_scene = scene_index;
    }
  })
}

function playerChange(path)
{
  showVal("playerChange: prepare [" + path + "]");

  xjsRun(function (source){

    showVal("playerChange: changing [" + path + "]");

    source.setValue(path)
    .then(function(source) {
      return source.setPlaybackPosition(plus_seconds);
    })
    .then(function(source) {
      return source.setPlaying(true);
    })
    .then(function(source) {
      return source.isPlaying();
    })
    .then(function(flag) {
      showVal("playerChange: changed and isPlaying = " + flag);
    });
  });
}

//main
playerChange(root_path + strategy['file']);

setTimeout(function() {
  changeScene(current_scene);
}, 3000);
```

And I will rewrite the code
```javascript
let target_active_scene = 2; //not the active scene number.

XJS.Scene.getActiveScene().then(function(scene) {
  return scene.getItems();
}).then(function(items) {
  // Assuming that we have only one item in the current scene, which is a media item :)
  return items[0].setValue(new_val)
}).then(function(item) {
  return item.setPlaybackPosition(0.0)
})
.then(function(item) {
  return item.setPlaying(true);
})
.then(function(item) {
  return item.getPlaybackPosition();
})
.then(function(pos) {
  console.log("get [" + new_val + "] at pos = " + pos);

  //change the scene
  showVal("scene is changing to [" + target_active_scene + "]");
  return Scene.setActiveScene(target_active_scene);
})
.then(function(ret_set_active_scene) {
  if (ret_set_active_scene)
  {
    showVal("scene is changed to [" + target_active_scene + "]");
    last_scene = scene_index;
  }
})
```

**My question is my second code block is correct?**
Thank you.

**Comment by dcefram** [comment]
The second code block should work since switching to a scene with a MediaItem will automatically play the MediaItem (as of the latest XSplit Broadcaster version).

Now, if you really need to know when the scene changes (probably for other logic that you might need), you can listen to `scene-load` event. Docs: http://xjsframework.github.io/api.html#/window/ExtensionWindow

ex:
```javascript
xjs.ExtensionWindow.on('scene-load', function(sceneId) {
  // do something here
});
```

**Comment by yoshi315** [comment]
OK, thank you very much.
This issue is done.
