### ISSUE TITLE
event for any item configuration change

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#104]
As mentioned is a few other issues (eg. #97 and #92), firing events when various item properties change would be very useful for a variety of plugin purposes. In addition to these events and maybe as  a first step before all the events can be individually implemented, it would go a long way to help if there was just a general "Item Changed" event that would emit the item id whenever anything happened to an item that would change its configuration (ie. anything that would affect the result of the `item.toXML()` function). That way a plugin would at least know when an item has been changed and be able to easily check if whatever property it cares about has been modified. Checking for a specific property whenever anything is modified isn't ideal, but it is a lot better then constantly poling.

Separate events for every property change would obviously be even better, but this seems like it would be almost as good for a lot of situations.

**Comment by Matrim-Cauthon** [comment]
Really great suggestion @paul-lrr !

We've filed this in our internal issue tracker (CPPCORE-1080), hopefully we don't run into too many technical barriers for this. I'll assign a milestone when we get an implementation inside XSplit.

**Comment by paul-lrr** [comment]
On a related note (not sure if this should be a separate issue) it would also be very useful to have an event emitted when a new item is added to a scene. Ideally with the item id so that a plugin could then query that new item for whatever info it needs.
