### ISSUE TITLE
loadConfig() within scene-load handler

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#11]
I am working on an extension that allows modifying several of the Items in a scene at once. When I first load the extension, I can get a list of the items in the current scene, iterate through them and `loadConfig()` on each to get their current settings. When the user switches to a different scene, the extension needs to load the items from the new scene and that is where I am having trouble. Within a `scene-load` handler, I can load all the items in the new scene, but if I try to `loadConfig()` on any of them I just get an empty object. Using looking at the items shows that they are loaded successfully and the config data is in the xml definition. Theoretically, I guess I could manually parse it from the raw xml, but that seems wasteful when `loadConfig()` is supposed to do what I want.

Sample code:
```javascript
extensionWindow.on('scene-load', function(){
	xjs.ready().then(Scene.getActiveScene)
	.then(function(currentScene){
		return currentScene.getItems();
		}).then(function(items){
            console.log(items[0]) //logs a normal Item object
			return items[0].loadConfig();
			}).then(function(config){
				console.log(config); //logs an empty object
			});
});
```
Cheers,
Paul

**Comment by dcefram** [comment]
Hi, I tried it out on my end, but I couldn't seem to reproduce it. The scenario that I had for trying it out is:
- HTML Plugin loaded on one scene
- HTML Plugin has its configuration modified (through its properties window)
- Other scenes are empty

I was able to get the configuration of the HTML Plugin as was expected.

Could you provide extra details on how you were able to encounter the issue? It would be of great help if we get to reproduce the issue on our end to debug this issue.

I'll update the label as a bug if we confirmed that its a bug :)

**Comment by paul-lrr** [comment]
I made a new presentation and a new Extension and tried it again, but I got the same result. 

To recreate the issue, make an extension using the following code:
```javascript
<html>
<head>
<script type="text/javascript" src="https://getfirebug.com/firebug-lite.js#startOpened"></script>
<script src="js/xjs.js"></script>

<script>
var xjs = require('xjs');
var extensionWindow = xjs.ExtensionWindow.getInstance();
var Item = xjs.Item;
var Scene = xjs.Scene;

initExtension();
extensionWindow.on('scene-load', function(){
   initExtension();
});

function initExtension(){
xjs.ready().then(Scene.getActiveScene)
    .then(function(currentScene){
        return currentScene.getItems();
        }).then(function(items){
            console.log(items[0]) //logs a normal Item object
            return items[0].loadConfig();
            }).then(function(config){
                console.log(config); //logs an empty object if called from scene-load
            });
}
</script>
</head>
<body>
</body>
</html>
```
(I am using firebug lite for debugging and console output)

Add the extension to xsplit and then put a few text/html sources on several scenes. When you launch the extension, it should execute `initExtension()` and correctly log the first item object in the scene and its config properties. When you switch to a different scene, evoking the `scene-load` handler (which is calling the same `initExtension()`) it will log the item and an _empty object_ instead of the config properties. As a further test, if you manually call the `initExtension()` function from the console, it works fine. It seems to be only in the event handler that it has problems.

**Comment by dcefram** [comment]
I made an extension plugin using the code that you provided, and it still worked on my end.

Can you confirm some details for me? You're running the plugin on the latest developer build of XSplit Broadcaster right? (Version 2.6.1509.3002)

and the xjs version would most likely be the latest 0.7.0?

If you are using the latest versions of both the client and the framework, could you try fetching the extension window's instance after xjs framework is initialized, ie:

```javascript
var xjs = require('xjs');
var Item = xjs.Item;
var Scene = xjs.Scene;
var _fetchConfig = function() {
  Scene.getActiveScene().then(function(scene) {
    return scene.getItems();
  }).then(function(items) {
    console.log(items[0])
    return items[0].loadConfig();
  }).then(function(config){
    console.log(config);
  });
}

xjs.ready().then(function() {
  var extensionWindow = xjs.ExtensionWindow.getInstance();
  extensionWindow.on('scene-load', _fetchConfig);

  _fetchConfig();
});
```

**Comment by SML-MeSo** [comment]
Hi, just for further verifications, does setting all the plugins to be "kept in memory" (checkbox at bottom of source properties dialog) help resolve the issue?

**Comment by paul-lrr** [comment]
Ah, that's it! It looks like Keep in Memory has to be enabled for it to work. Thanks for the help.

The version of XSplit I am running is 2.6.1509.1003, so I guess I am a little behind. I originally got this version through the XSplit JS Framework - Developer Preview email. Where do I go to get the newer version?

As a side note, it would be nice if there was an option to make "Keep in Memory" the default. I usually go through and check that box all my sources anyway as it makes everything run smoother and more predictably (especially scene transitions) and even using upwards of a dozen different image, video, html and camera sources on all 12 scenes, it doesn't seem to make xsplit take an excessive amount of memory.

**Comment by dcefram** [comment]
Hi, you could get the latest XSplit developer build at the website (http://xjsframework.github.io/quickstart.html). We do not yet prompt developers if there's a new developer build available, sorry about that.

The problem with setting Keep in Memory be default is that it _could_ take a lot of memory depending on the items in your presentation. I could however raise this issue to the guys who handles this if it makes sense to add up an option on the settings to enable the "Keep in Memory" by default.

As of now, all I could think of is to make a plugin that would auto set Keep in Memory on all items when the scene loads using `setKeepLoaded` method.

**Comment by SML-MeSo** [comment]
It's a good thing that setting "Keep in Memory" for the sources worked for you. I think what happens here is that the "scene-load" event in the extension is simultaneous with the loading of sources, such that there may be times when the extension tries to get the plugin configurations before they are prepared by the plugins themselves, hence the blank result.

**Comment by Matrim-Cauthon** [comment]
Hi Paul, I'll be closing this item as a workaround was found. Please feel free to file a new one if you run into any new related issues.
