### ISSUE TITLE
Having XJS framework on an HTML and an iframe within it may cause wrong videoitem properties to be returned

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#112]
Currently, whenever attaching an item, we reference their IDs in a slot map so that we won't have to attach them again on successive videoitem property calls. However, these may fail on main frame-iframe instances, both with XJS framework included. Both of them share a videoitem instance such that when calling AttachVideoitem1 on the main frame with a specific ID, then calling also AttachVideoitem1 on the iframe with another ID will overwrite the videoitem attached at slot 1 for the both of them. Therefore, when mainframe tries to access the properties of the former ID, it will not call attach anymore since in its slotmap, it still has the item as slot 1 when really, it isn't because of the overwrite. It will erroneously return the property which is really for the latter ID (from iframe).

possible resolutions (either of the two):
- do not use the slot map and either always attach everytime we try to access a videoitem property or always detach afterwards
- have a flag somewhere in the framework which user needs to toggle if to be used in an iframe and just do the above behavior when toggle is on

**Comment by Matrim-Cauthon** [comment]
I'm in favor of the flag, but reversing the toggle.

Meaning, there is a special optimization flag which will work fine except when iframes are involved.

That way, we always preserve the fact that our framework should work out of the box without special configuration.

**Comment by virn** [comment]
For the flag, we have two options on setting this.

- Expose a variable, "useSlot" somewhere in the framework.
- Create a configuration object, something like "slotOptimization", where we can set the "useSlot" variable.

**Comment by Matrim-Cauthon** [comment]
I forgot to mention it here, but @SML-MeSo and I previously discussed actually just not implementing the optimization flag, because we don't have any benchmarks yet on whether it has a noticeable effect.

In my opinion, we can just fix the bug to work for all instances (meaning, we always reattach for any internal API calls). This is probably the quickest and simplest resolution for this item. cc @dcefram

**Comment by virn** [comment]
6604174
