### ISSUE TITLE
Add audio, video and output encoded values in Channel class passed by stream-end event of ChannelManager

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#114]
Right now, the stats property of the Channel class passed by stream-end event of the ChannelManager class only consists of frmdropped and frmcoded values, unlike from the Channel object returned by getActiveStreamChannels which also has audio, video and output encoded values.

**Comment by SML-MeSo** [comment]
XBC change is verified in XBC v.2.8.1607.1938, making the issue ready for resolution

**Comment by virn** [comment]
Fixed on 98a9ed2
