### ISSUE TITLE
HTMLItem.setURL method excludes the set browser configuration

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#117]
The getURL method automatically removes browser configuration when returning the URL. Following that behavior, setURL method should then just automatically affix the browser configuration for the item.

**Comment by Matrim-Cauthon** [comment]
Perhaps this is not so much a bug, as a lack of options. Do you think there might be cases when a clean browser configuration is desired?

**Comment by SML-MeSo** [comment]
I was just under the notion that since getURL automatically remove config in its return, its corresponding set method should then automatically affix it. In case a clean browser configuration is desired, user/developer can opt to use setValue method as inherited from Item class.

**Comment by Matrim-Cauthon** [comment]
I think that's fair. Let's make sure to document that behavior in generated docs.
