### ISSUE TITLE
sources-list events not firing in xsplit 2.9

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#124]
I'm having a problem with the new version of xsplit (2.9.1611.1622) where the _sources-list_ events (`sources-list-highlight`, `sources-list-select`, etc) are not firing. The `scene-load` event works but something like
```javascript
var xjs = require('xjs');
var ExtensionWindow = xjs.ExtensionWindow.getInstance();
xjs.ready().then(
	ExtensionWindow.on('sources-list-highlight',function(id){console.log(id)});
);
```
never seems to be activated even though I see it in the __handlers_ object of ExtensionWindow

**Comment by Matrim-Cauthon** [comment]
@virn can you take a look at this please? If the feature broke as of the latest XBC 2.9 release, let's see if we can add it to xjs@2.0.0 or a hotfix afterwards.

**Comment by virn** [comment]
@paul-lrr can you try removing `getInstance()`, it should only be used when you manipulate the extension window itself (resize, setTitle).

**Comment by paul-lrr** [comment]
Ok, that did seem to be the problem. When I register the `.on` handler with `xjs.ExtensionWindow.getInstance()` those events don't fire, but using `xjs.ExtensionWindow.on` directly gives me the proper results. Using `getInstance()` definitely used to work and still works with `scene-load`. Also, after getting some confusing results, I discovered that if you register `sources-list` events with `xjs.ExtensionWindow.getInstance().on()` nothing happens, but if you then register an event with  `xjs.ExtensionWindow.on()` _the previously registered `getInstance()` events start firing as well_. 

There is definitely something a little weird going on, but for now always directly registering with `xjs.ExtensionWindow.on` seems to be a good solution.

**Comment by Matrim-Cauthon** [comment]
Yeah, there are definitely some weird things going on here, and I think we definitely want to revisit the design of this part of the code someday. Personally, I think there could be better ways to implement the event system we have, but there are no immediate plans to make big changes here.

For now, we won't touch this for our upcoming releases, but I'll leave this issue open until we decide on a suitable resolution for a future update.

**Comment by virn** [comment]
After further discussions, it is decided that we remove the **getInstance** call for ExtensionWindow, since technically, there should only be one instance per Extension.
Also, all methods for ExtensionWindow are now set as static and updated accordingly to work with this change.
