### ISSUE TITLE
Update debugger xsplitprops.html to XSplit 2.9 build

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#125]
We need to replace the build at our [debugging tutorial](xjsframework.github.io/tutorials.html#/debugging).

This needs to be a modified fork of the `xsplitprops.html` we shipped with XSplit 2.9.

**Comment by SML-MeSo** [comment]
No major/breaking changes which affects plugin development have been made to XBC source properties dialog which merits this to be done for 2.0. Moving this item after the 2.0 release

**Comment by Matrim-Cauthon** [comment]
Won't fix this item, because there have been no breaking changes that merit creating a new developer build of this HTML.
