### ISSUE TITLE
 Xsplit .Net Framework Initialization Error

### ISSUE THREAD

**Issue by wtankwey** [xjsframework/xjs#132]
When I open Xsplit V.2.9 (2.9.1701.1616), I get the following Error message:
"Please set registry key
HKLM\Software\Microsoft\.NetFramework\InstallRoot to point to the .Net Framework install location"

But Xsplit Broadcaster is running as if there's not problem.

Can you please look into that and let me know how to resolve this issue?

Have a good day!

Willy
[My screen shot.docx](https://github.com/xjsframework/xjs/files/885942/My.screen.shot.docx)
[DxDiag.txt](https://github.com/xjsframework/xjs/files/885943/DxDiag.txt)

**Comment by Matrim-Cauthon** [comment]
Hey there, thanks for using XSplit!

This Github is meant for reporting issues with our XSplit JS Framework, for those interested in writing their own plugins. I'd like to direct you to our support desk for problems with XSplit itself: http://supportdesk.xsplit.com/

Please file your issue there so you can more easily receive product support. Thanks!
