### ISSUE TITLE
Avoid overriding global callbacks

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#137]
In certain contexts, it can be necessary to run `xjs` together with code that directly accesses the raw Broadcaster API. This constitutes issues regarding build/execution order, because callbacks like `OnAsyncCallback` are directly replaced by `xjs`.

We need to ensure that the framework simply wraps existing definitions of relevant global functions (as some kind of middleware).

**Comment by virn** [comment]
Wrapped all window callbacks before xjs overriding said callbacks.
