### ISSUE TITLE
Create Screen Region class

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#14]
(moved from internal issue tracking: PLG-199)

Currently in PLG-199 branch, and assigned to me for review

**Comment by Matrim-Cauthon** [comment]
Hey @dcefram, I think we should also include functionality to actually add a screen region; currently, the PLG-199 branch only seems to be able to detect already placed screen region sources.

Finally, please add the necessary classes to the API doc modules. Thanks!

**Comment by dcefram** [comment]
We will file another issue for the task of adding a screen region item to a scene.
