### ISSUE TITLE
User Input data ?

### ISSUE THREAD

**Issue by jamesswyr** [xjsframework/xjs#144]
Hello Xsplit-Team,

is there any way to get User Input data in your framework?
I know that it is possible because the Scene switcher plugin uses Hotkeys, but I couldnt find the responsible class in your API documentation.
Or is it possible to get the scene switcher .js file ?

Thank you very much and kind regards,

js

**Comment by SML-MeSo** [comment]
Hi, @jamesswyr!

If you're pertaining to keypresses, maybe the DLL class can help you. See http://xjsframework.github.io/api.html#/core/Dll and http://xjsframework.github.io/tutorials.html#/dll.

Also, I think a more suitable sample plugin would be this one, https://github.com/xjsframework/input-visualizer

**Comment by mikeybanez** [comment]
This seems to have been resolved already. Closing issue.
