### ISSUE TITLE
No Documentation on Using Custom DLLs

### ISSUE THREAD

**Issue by gyroninja** [xjsframework/xjs#145]
Since XJS does not expose a way to create a TCP socket I've figured my best option is just to make a helper DLL to handle it.  Unfortunately there is no documentation on how this DLL should be created. I've seen mentions of calling a callback with the string you are passing back, but I'm not entirely sure what needs to happen.
If you could get me more information on what I need for a DLL to function with my plugin that would be great. :-)

**Comment by Matrim-Cauthon** [comment]
Hey there, in the "Creating DLLs" section of [this page](http://xjsframework.github.io/tutorials.html#/dll) is a downloadable PDF for those interested in creating their own DLLs. Feel free to leave another comment in this issue if documentation is insufficient.

**Comment by gyroninja** [comment]
@mikeybanez I've finally come back in order to try and make a custom dll again. These issues are likely due to my unfamiliar with working with Windows. Another difficulty is that there is no sample project I can check against to see if I'm doing it correctly.
Here is the code which I'm currently trying to compile.
```c
#include <stdio.h>
#include <windows.h>

[uuid("9A554D8A-912F-4F1E-9A26-CC002B3B99BD"]
DECLARE_INTERFACE_(IXSplitScriptDllContext, IUnknown) {
    STDMETHOD(Callback)(BSTR functionName, BSTR* argumentsArray, UINT argumentsCount) PURE;
}

BOOL WINAPI XSplitScriptPluginInit();
void WINAPI XSplitScriptPluginDestroy();
BOOL WINAPI XSplitScriptPluginCall(IXSplitScriptDllContext *pContext, BSTR functionName, BSTR *argumentsArray, UINT argumentsCount, BSTR *returnValue);

BOOL WINAPI XSplitScriptPluginInit() {
    return TRUE; // Don't connect to server here. People might not want to even use this plugin
}

void WINAPI XSplitScriptPluginDestroy() {

}

BOOL WINAPI XSplitScriptPluginCall(IXSplitScriptDllContext *pContext, BSTR functionName, BSTR *argumentsArray, UINT argumentsCount, BSTR *returnValue) {
    printf("Hello World!\n");
    returnValue = SysAllocString(L"Hello XSplit");
}
```
With MinGW and gcc the first compile error I get is. `error: expected identifier or '(' before '[' token.
With VS I get `"uuid" attribute cannot be used here"`

The PDF seems to be helpful, but I feel like I'm missing something crucial in order to make it able to be compiled. It would be great if you were able to see the fatal mistake I made with my code or were able to upload an extremely minimal sample project.
