### ISSUE TITLE
Node.js : Error at the start

### ISSUE THREAD

**Issue by MrPadRpg** [xjsframework/xjs#147]
Hi,

I installed the framework with NPM (npm install xjs-framework) for my Node.js project.
I included this line in my code : 
`var xjs = require('xjs-framework');`

When I launch Node.js, I've got this error :
```
node_modules\xjs-framework\src\index.ts:1
(function (exports, require, module, __filename, __dirname) { export * from './util/color';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>
```

Did I miss something ?

**Comment by Matrim-Cauthon** [comment]
Hi, thanks for your interest in trying out the framework.

It appears that you are requiring the original source in TypeScript, which makes use of ES2015 modules already. Unfortunately, Node.js doesn't support these natively yet, so you have two options:
1.) The simple option is to use the built file already, 
`require(./node_modules/xjs-framework/dist/xjs.js)`
2.) Alternatively, if you want to build directly from the source, you'll want to use Webpack together with the necessary loaders (including the TypeScript loader.) For more info on this, please see: http://xjsframework.github.io/tutorials.html#/es6

I hope this solves the issue.

**Comment by MrPadRpg** [comment]
Hi,

Thanks for your answer.
I already try to put `require('./node_modules/xjs-framework/dist/xjs.js')` in my code but I have a different issue (window not define in line 1375 of xjs.js)

I will try to build from the source.

Thanks.

**Comment by Matrim-Cauthon** [comment]
@MrPadRpg I think I see the problem much more clearly now --- xjs is not meant to be run in a Node.js environment. It should be targeted to browsers as XSplit's source and extension plugins are all HTML pages.

Might I know why you need Node for your project?

**Comment by MrPadRpg** [comment]
I need Node because my project is developed on Node since the beginning :) (and it's not only for xSplit).
Thanks for your answer, I will try to integrate this in my project in a another way.

Thanks

**Comment by Matrim-Cauthon** [comment]
I see. The framework requires the use of `window` because it communicates with the application through APIs defined on the global `window` object. Even during initialization, a number of `window.<function>` calls are made to properly configure itself.

I'm quite curious to know the details of your project, if you don't mind sharing them?

**Comment by MrPadRpg** [comment]
Not a problem.

I'm a rpg GM and I will stream (or just record) my games with xSplit. When my players won't use webcams, I want to see who's talking in the video. 
For that, I use the discord API in Node to detect who's talking and I want to show that in xSplit. 
Currently, I use socket io to update the color of a web page that I show behind the avatar of the player in xSplit. It's a little heavy and I'm not sure that it will be strong enough to stay stable during the time of the games so I want to take a look at the xsplit js API to see if I can interact directly with xSplit.

**Comment by Matrim-Cauthon** [comment]
Thanks for that.

As of the latest release (2.2.0) we do have a [feature in beta](http://xjsframework.github.io/tutorials.html#/remotexjs) that allows you to create your own Extension ("proxy") that can communicate directly with your Node server ("remote") through any mechanism you wish (Web Sockets, RTC Data Channels, etc.). However, the problem of server-side xjs not functioning properly still remains.

I've filed an issue (#148) to see if we can feasibly address the root problem. This is quite an interesting use case that only makes sense in the context of remote xjs 😄

**Comment by mikeybanez** [comment]
Closing this issue now. Server-side xjs will not be supported for the time being, but we will keep #148 open for any additional discussion in this area.
