### ISSUE TITLE
Documentation error in API Reference for Dialog Class

### ISSUE THREAD

**Issue by theRTC204** [xjsframework/xjs#172]
The return type on the `show()` function is incorrectly listed as `Dialog` when it actually returns a `Promise<Dialog>`. Additionally the usage example for the class incorrectly shows chaining `.getResult()` when it must be used inside a promise chain.

**Comment by theRTC204** [comment]
Threw in a PR for this, since it's just docs updates

https://github.com/xjsframework/xjs/pull/173

**Comment by virn** [comment]
Hi @theRTC204 , thanks for noting those errors on the documentation. I had to make a different commit for it though, because your merge request has something missing on it.

**Comment by theRTC204** [comment]
Hahahaha, whoops! I guess that's what I get for quickly throwing together an MR instead of actually using the code I wrote in my extension.

Thanks for taking care of this @virn!
