### ISSUE TITLE
Trouble With Making DLL / Sample code for DLL

### ISSUE THREAD

**Issue by gyroninja** [xjsframework/xjs#174]
I am trying to get a test dll compiled for xsplit. The issues I'm facing are from my inexperience in the Windows ecosystem. It would also be easier to figure how to make a proper dll if there was an extremely basic sample project.
Anyways, here is the code which I'm currently trying to compile.
```c
#include <stdio.h>
#include <windows.h>

[uuid("9A554D8A-912F-4F1E-9A26-CC002B3B99BD"]
DECLARE_INTERFACE_(IXSplitScriptDllContext, IUnknown) {
    STDMETHOD(Callback)(BSTR functionName, BSTR* argumentsArray, UINT argumentsCount) PURE;
}

BOOL WINAPI XSplitScriptPluginInit();
void WINAPI XSplitScriptPluginDestroy();
BOOL WINAPI XSplitScriptPluginCall(IXSplitScriptDllContext *pContext, BSTR functionName, BSTR *argumentsArray, UINT argumentsCount, BSTR *returnValue);

BOOL WINAPI XSplitScriptPluginInit() {
    return TRUE; // Don't connect to server here. People might not want to even use this plugin
}

void WINAPI XSplitScriptPluginDestroy() {

}

BOOL WINAPI XSplitScriptPluginCall(IXSplitScriptDllContext *pContext, BSTR functionName, BSTR *argumentsArray, UINT argumentsCount, BSTR *returnValue) {
    printf("Hello World!\n");
    returnValue = SysAllocString(L"Hello XSplit");
}
```
With MinGW and gcc the first compile error I get is. `error: expected identifier or '(' before '[' token.`
With VS I get `"uuid" attribute cannot be used here"`

The PDF seems to be helpful, but I feel like I'm missing something crucial in order to make it able to be compiled. It would be great if you were able to see the fatal mistake I made with my code or were able to upload an extremely minimal sample project. I could also be making a mistake in assuming that it's possible to make a dll with using C.

**Comment by mikeybanez** [comment]
Hey @gyroninja, apologies for the late reply. At first glance it appears that the lack of a closing `)` in your uuid line is the culprit here.

But I will get you a sample project as a reference so you can try it out. I will send a link here shortly.

(Also, for XSplitScriptPluginCall, make sure you always return true if you are handling a method, and false otherwise. If this is not done, it can cause other DLLs to not work.)

**Comment by mikeybanez** [comment]
Our core developers have provided me with this sample DLL project. [Can you give it a try](https://drive.google.com/file/d/0B3kQ9zbIw4yAdldPYU5kcC0yWjA/view?usp=sharing)?

**Comment by gyroninja** [comment]
Thanks, I'll try it out in a few hours.

**Comment by gyroninja** [comment]
@mikeybanez I've managed to get my project compiling. The main thing I was missing was including in `combase.h` and it's dependencies. It also appears that some of the headers in the sample project seem to be under a proprietary license.
If I'm able to get my dll working, I'll report back here and close the ticket.

**Comment by gyroninja** [comment]
@mikeybanez I got it working with just a few little changes on my end. I would recommend making these changes to the pdf:
* Provide a download for combase.h and wxutil.h
* Instruct the user to put both `#include altbase.h` and `#include combase.h` into their stdafx.h
Those two things were the only things that were missing from the documentation on getting it to compile.
I would also like to ask about a difference with IXSplitScriptDllContext with the header you provided.
Documentation:
```C++
[uuid(9A554D8A-912F-4F1E-9A26-CC002B3B99BD)]
DECLARE_INTERFACE_(IXSplitScriptDllContext, IUnknown)
{
	STDMETHOD(Callback)(BSTR functionName, BSTR *argumentsArray, UINT argumentsCount) PURE;
};```
Yours:
```C++
[
	uuid(9A554D8A-912F-4F1E-9A26-CC002B3B99BD)
]
DECLARE_INTERFACE_(IXSplitScriptDllContext, IUnknown)
{
	STDMETHOD(Callback)(BSTR bstrFunc, BSTR *bstrParams, UINT nParams) PURE;
	STDMETHOD(IsValid)(HANDLE *pEvBreak) PURE;
};```
Is the IsValid method something internal that I should forget about, or is it missing from the documentation?

**Comment by mikeybanez** [comment]
`isValid` internally checks if the context is valid (browser is not null).

Thank you so much for your comments and investigation! Since you managed to compile it properly, I'll mark this issue as closed for now. But it looks like we really need to review the DLL documentation, so we will consider your feedback to update it soon.
