### ISSUE TITLE
Update 'preset' properties to 'scene'

### ISSUE THREAD

**Issue by mikeybanez** [xjsframework/xjs#175]
As of CPPCORE-1391, `presetX` properties are being renamed to `sceneX`. For compatibility, the old names are still there, but after the next XSplit release where these changes are merged, we should rename existing properties/functions that are affected.

**Comment by mikeybanez** [comment]
We shouldn't assign this to a specific xjs version yet, until we know when the changes will be merged into the main branch of the app. But @dcefram @SML-MeSo just note these changes.

**Comment by dcefram** [comment]
I assume that it's safe to rename `preset*` to `scene*` without considering backwards compatibility with older XBC versions?

**Comment by mikeybanez** [comment]
It should be safe to do so now. The name change within core components was already done in 2017. The XSplit versions on the website should all support `scene*` property names.
