### ISSUE TITLE
getSceneId in preview returns NaN [Regression]

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#180]
Having a problem with the `item.getSceneId` method returning NaN when the item is on the Preview window. This is referenced in Issue #113 _and was resolved in xjs v1.4.1_. At some point, that fix seems to have been reverted, though and the problem exists again in v2.5.0.

This is the fixed version of the `getSceneId` method in v1.4.1 (line 5729 in xjs.js)
```javascript
  /**
     * return: Promise<number>
     *
     * Get (1-indexed) Scene ID where the item is loaded
     *
     * #### Usage
     *
     * ```javascript
     * item.getSceneId().then(function(id) {
     *   // The rest of your code here
     * });
     * ```
     */
    Item.prototype.getSceneId = function () {
        var _this = this;
        return new Promise(function (resolve) {
            if (_this._sceneId === 'i12') {
                resolve('i12');
            }
            else {
                resolve(Number(_this._sceneId) + 1);
            }
        });
    };
```

**Comment by virn** [comment]
Checked on the previous merges and saw that the fix was overridden on one of the merges for v.2.0.0.
I will be adding the fix on the 2.6.0 which will be released this month.
