### ISSUE TITLE
DLL Call not Accessible / Where to put Custom DLL

### ISSUE THREAD

**Issue by gyroninja** [xjsframework/xjs#182]
I haven't worked on my extension for about a month and half and when I came back and updated xsplit, my extension seemed to stop working.
I have a feeling it has to do with loading the dll because the code I have for calling it did not change and my code for granting access still works. If I change the string to the path of the dll file, it returns the same error so I have a feeling it is unable to find it in the first place.
I have tired placing my dll in `%APPDATA%\SplitmediaLabs\XSplit Broadcaster\install\1613A97\x64\Scriptdlls` and `C:\Program Files (x86)\SplitmediaLabs\XSplit Broadcaster\Scriptdlls` but my extension still did not work.
Do you know if a recent update messed with the functionality of dll.load, or do you think an update had wiped out where I put my dll?

I know I had this working before, so I am not sure what I can do myself to further investigate the bug since what I was presumably doing before does not work anymore.

**Comment by mikeybanez** [comment]
Can you try going to Tools > Settings > Advanced, then check if "Enable developer mode" is checked? Unsigned DLLs are not loadable by default, unless you are in lowered security from Developer Mode.

**Comment by gyroninja** [comment]
@mikeybanez Yes developer mode is enabled and I gave permission to my extension.

**Comment by mikeybanez** [comment]
The latest XSplit is now a 64-bit application. All existing DLLs were updated to 64-bit as well. Can you try to do the same for your custom DLL?

**Comment by gyroninja** [comment]
@mikeybanez Yep, that seems to be it.

**Comment by gyroninja** [comment]
Thanks, after making a 64 bit version and dropping it in the Program Files (x86) location it works.
