### ISSUE TITLE
xjs.Environment checks return undefined

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#184]
In the new xjs 2.6, the xjs.Environment methods like `isExtension()` and `isSourcePlugin()` are returning undefined instead of true/false. Since various other classes use these methods to check the environment, this also breaks a bunch of other stuff like `xjs.Extension.getInstance()`. I suspect the issue is something to do with changing from window to window_1 (which I assume was to get the library to work in a non-browser environment).

**Comment by virn** [comment]
@paul-lrr I'd like to confirm if you're doing the Environment checking after `xjs.ready` is called.

The change you've mentioned(#177), other than it's intended purpose, enforces that Environment checking, initialization, and all other xjs calls should be done after `xjs.ready`.

**Comment by paul-lrr** [comment]
Ah, ok. That seems work.
Previously I had been using `xjs.Environment` to check if the extension/plugin is loaded in xsplit  _first_ and if not running in xsplit, I just skipped the `xjs.ready()` and any xjs commands all together. I realize now, with  xjs.Remote, that external scripts can access xsplit functionality so we always have to use `xjs.ready()`. Prehaps it would be good to mention this change and how to migrate in the wiki or the xjsframework.github.io docs

**Comment by virn** [comment]
This is definitely something that we should emphasize on our docs and wiki. Will definitely make some changes on the wiki and docs, and describe this change/requirement properly.
