### ISSUE TITLE
Implement scene-delete and scene-add events for all scenarios

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#191]
Right now, our scene-add and scene-delete events have certain limitations, such as not being triggered when:

- scene add by `New Scene` in XBC
- scene add by `Duplicate Scene` in XBC
- scene add when setting active scene to non-existing scene
- any other API call which may remove or add scene
- scene delete by `Delete Scene` in XBC (I'm guessing via API)
- scenario when deleting the only scene, wherein current scene is deleted, then a new scene is added (no events for both, except when pressing delete

check on work log comments in CPPCORE-1433 for reference

**Comment by virn** [comment]
Fixes for this issue are done together with the changes on #193.

**Comment by nelson-temporal** [comment]
Tested
