### ISSUE TITLE
Output class doesn't return displayName and returns XML-encoded channel name

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#194]
Right now, the list being received in getOutputList does not always automatically reflect the list present in XBC's Output menu. This is because the names being returned in getOutputList are the actual channel names while the ones listed in the Output menu are their corresponding display names.

And while we're at it, the channel names are xml-encoded, such that using startBroadcast in channels with `xml-reserved` characters in their names yield to wrong start broadcast calls

**Comment by nelson-temporal** [comment]
Tested
