### ISSUE TITLE
Support re-initializing the `sendMessage` method used by Remote

### ISSUE THREAD

**Issue by ravenjohn** [xjsframework/xjs#199]
xjs only allows setting the sendMessage method on `.ready()` which means it can only be done once. Since the connection used for sending messages can be replaced. It would be better if xjs allows the `sendMessage` function to be set again.
```js
xjs.ready({
    remote: {
        type: 'proxy',
        sendMessage: peerConnection.send,
    }
})
```

Proposed:
```js
xjs.Remote.setSendMessage(peerConnection.send);
```

Workaround available:
```js
xjs.Remote.sendMessage = peerConnection.send;
```

**Comment by virn** [comment]
I'll also be including the method to `xjs.Remote.setRemoteType` for instances where you need to set the remoteType on the extension to be executed locally, to avoid using the current workaround.

**Comment by mikeybanez** [comment]
Don't forget to add these changes or additions to the tutorial article about Remote.
