### ISSUE TITLE
Access Denied to zipped framework on xjsframework.github.io

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#2]
Not sure if this is the best place to for reporting bugs in the xjsframework.github.io site, but the link to the zip file (http://cdn2.xsplit.com/xjs/download/sourceplugin.zip) results in a Access Denied error
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>938473717F6EFE2A</RequestId>
<HostId>
fB1DXuqYGV/IXFb1ZPiW3fKgTMeY2193jwy0L1ThlSbsVCi5AcvT3rwAN/xCksCq
</HostId>
</Error>
```

**Comment by dcefram** [comment]
Yup, this is the correct place to report bugs regarding our xjs website. :)

The issue with that is our uploads to our cdn takes time to actually propagate, but the files were actually uploaded 4hours ago. I will followup this issue with our infra and get back here asap.

**Comment by dcefram** [comment]
The link should work by now. I will be closing this issue. If you have any question or found any other bug, please do file another issue.

Cheers
