### ISSUE TITLE
Support for builds as npm modules

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#20]
Just as we have generator-xjs as a node module, there is some need to publish the framework similarly.

**Comment by dcefram** [comment]
Since we have a package.json, it would be pretty simple to accomplish this task.... **BUT** someone already took the 'xjs' name on npm. We need to think of another alternative name for this :(

Probably xjs-framework will do? watcha think?

**Comment by Matrim-Cauthon** [comment]
Looks good to me. We may need to update our website's getting started page to reflect this, too. If we do that, it makes sense to also specify that we recommend using a fixed package version when installing the module, especially since we are still in alpha and may make breaking changes quite often.
