### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by nayaboi** [xjsframework/xjs#206]
I bought the 1month subscribtion to xsplit but it wasnt activating so i bought the 3 month and its not activated yet. I was wondering if there is any way to cancel the 3 month because i aready have 1 :/

**Comment by mikeybanez** [comment]
Sorry, this is not the correct support channel for XSplit licensing issues. This is the repository for our XSplit JS Framework for creating plugins.

You can start a conversation with XSplit support at https://www.xsplit.com/support.
