### ISSUE TITLE
Native resolution of Camera source

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#207]
At the bottom of the properties window for camera and media sources, it lists the "native" resolution of the source in brackets beside the current dimensions. This is handy to, among other things, let you know if you have scaled a source to be larger then its native resolution or if you want ot set a source to 100% of its original size. I have been trying to find this information through xjs and for media sources, the `getFileInfo` method lists the native video/image dimensions, but I cannot see a way to get that info from a camera source. It is shown at the bottom of the source properties windows, so xsplit seems to have the information, but is it available through xjs?

**Comment by mikeybanez** [comment]
@SML-MeSo @ravenjohn I think we can also sneak this into the 2.8.0 release as the release is almost done.
