### ISSUE TITLE
Sources-list-select event in split mode

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#208]
I have an extension that is listening for `sources-list-select` events but I don't get anything when I select sources in a preview window (whether on the stage or in the source list). The event also doesn't seem to fire in split view. Is it intentional that preview windows don't fire events? If so, is there a way to indicate that I want preview window events?

simple example code:
```javascript
xjs.ready().then(() => {
	xjs.ExtensionWindow.on('sources-list-select', function(itemId) {
		console.log(itemId)
		});
	});
//logs the selected item id when an item is selected in a regular scene
//does nothing when item is selected in preview window
```

**Comment by SML-MeSo** [comment]
Yes, it was our earlier intention not to emit events from the preview editor. We would have to revisit our way of handling events if we would support it in order not to affect previous implementations that handle events only for main view. Oh, and `sources-list-select` events indeed work with split view, but for now, only when called when XBC is already in split view. Will be adding fix for it within this issue.

**Comment by nelson-temporal** [comment]
Validated on split mode.
We will revisit preview mode in the future.
