### ISSUE TITLE
Create composable search functions

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#22]
For our own sanity :wink: , we will rework our item and scene search functionality into composable and extensible functions. This will solve the need for the multitude of possible use cases.

This will solve issues similar to #9 and #10.

**Comment by dcefram** [comment]
Passing to @Matrim-Cauthon for a quick review. Also please do note that I renamed the method `searchAllForItemName` to `searchItemsByName` which also now implements the generic/composable search function `filterItems`.

**Comment by Matrim-Cauthon** [comment]
I think this works but perhaps we should consider avoiding ItemType checking (in the documentation comments), because of complexities with a non 1:1 correspondence between an ItemType to an actual set of functions/interfaces.
