### ISSUE TITLE
Config window breaks when plugin from UNC path

### ISSUE THREAD

**Issue by misha-plus** [xjsframework/xjs#220]
Hello.
I found a bug -- config window is broken when the plugin is added from UNC path. The config window didn't show any tab, reload button, just gray window.

In particular, this problem will be when plugin directory shared from Mac in Parallels VM.

#### Details
When I add a layer to the scene via HTTP, like `http://mbp:2015/` the plugin works correctly.
Local file, like `C:\my-plugin\index.html` works correctly.
But UNC file path, like `\\share\my-plugin\index.html` from shared brokes config window.

`index.html` have this meta tag for config:
```html
<meta name="xsplit:config-url" content="config.html">
```

**Comment by SML-MeSo** [comment]
Upon investigation, it is indeed on the side of the dialog in XBC. Hopefully, the fix will be integrated in the next release. Will further comment when fix is available.

**Comment by misha-plus** [comment]
Ok, thank you

**Comment by SML-MeSo** [comment]
Oh, sorry for the late update, but this should addressed already on the latest release, XBC v. 3.4.1806.2229
