### ISSUE TITLE
getCurrentSource returns basic Source object, not the type-specific ones

### ISSUE THREAD

**Issue by tbogard** [xjsframework/xjs#221]
Requirements:
XBC 3.4
XJS 2.8.1

example:
```
 xjs.ready()
  .then(Item.getCurrentSource)
  .then(function(item) {
    myItem = item;
    return item.loadConfig();
  })

```
error: loadConfig is not defined on item.

reverting to XBC 3.3 fixes the issue. XJS 2.8.1 working fine on XBC 3.3

**Comment by mikeybanez** [comment]
@SML-MeSo, this would be good to check now, to verify if the app needs to be patched (we are planning an upcoming M37-FB update).

**Comment by SML-MeSo** [comment]
Upon checking, issue may have been brought about by the changes for #216. Please note that issue can only be replicated in the minified version. For fixing

**Comment by tbogard** [comment]
checked with the provided source, still getting null on Item.getCurrentSource() promise: 
![image](https://user-images.githubusercontent.com/1978642/43025680-b9d984e0-8c40-11e8-8c4c-fc89c3f78bbd.png)

Not sure what to do at the moment, but this is leaving me to tell my client to wait until a definitive fix appears.
