### ISSUE TITLE
Allow `addToScene` calls to return UIDs of newly added sources

### ISSUE THREAD

**Issue by mikeybanez** [xjsframework/xjs#232]
We would want to reliably know the ID of a source that has been programmatically added to a scene through `xjs`, without doing all kinds of hacky workarounds. Currently, our `addToScene` promises always resolve with a boolean (potentially always true?), but we can extend this by returning a string ID instead.

For implementation, we can test out using the events listed in CPPCORE-1551. Please note that there are performance considerations here, because this currently requires to subscribe to events using `AppSubscribeEvents`. We may need to make this behavior opt-in.

**Comment by mikeybanez** [comment]
Note that this is very similar to the first point in #122 (but let's keep that issue open because 3.0.0 might look very differently).

But it might be a worthwhile idea to return `Source` items immediately instead of the raw ID. Something to discuss with @SML-MeSo just before we start to implement. (There may be cases related to pasting or with linked items which need to be studied first)

**Comment by nelson-temporal** [comment]
Done.
To enable returning of item id of added items ready must have config value { listenToItemAdd: true }.
e.g. 
xjs.ready({
	listenToItemAdd: true
}).then(() => {
	//your codes here
});
