### ISSUE TITLE
XBC 3.4 and XJS 2.8.0 weird glitch

### ISSUE THREAD

**Issue by tbogard** [xjsframework/xjs#233]
Hello guys

on XBC 3.3, the plugin I had for matcherino worked with no problems in spite of the glitch previously reported.

on XBC 3.4 the panel of properties didn't show up leaving the content empty:
![image](https://user-images.githubusercontent.com/1978642/44498550-23e98800-a64d-11e8-9ff0-4a19889fa6e1.png)

while debugging the source with `xsplitprops.html`, it suddenly works out of the blue:

![image](https://user-images.githubusercontent.com/1978642/44498613-85a9f200-a64d-11e8-944a-f72c195d3cef.png)

puzzled with this problem, I checked over the terminal debugger and I found this: `OnActivated is not defined`

![image](https://user-images.githubusercontent.com/1978642/44498639-aeca8280-a64d-11e8-8cd9-1bfa572244f4.png)

It is unknown to me what could be the real issue since for some weird reason, the plugin works ONLY with the inclusion of `xsplitprops.html`

**Comment by SML-MeSo** [comment]
Closing this issue since this has been addressed in the reporter's side, and no further reports have been done afterwards.
