### ISSUE TITLE
Allow adding of web sources programmatically

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#24]
Currently we can change the URLs for existing web sources, but there is no feature to create an entirely new HTML source on the stage.

**Comment by hlevring** [comment]
@dcefram so if that is not already there then how was it possible for Tnotifier to add a URL to stage from an extension?

**Comment by Matrim-Cauthon** [comment]
@hlevring for that plugin we resorted to our using our native calls to add the URL.

**Comment by Matrim-Cauthon** [comment]
Added the Url class in the System module. I figured this makes sense because local URLs are also accessible. (In any case, usage of the framework's classes currently does not require knowledge of source code 'namespaces' anyway.)

For review.
