### ISSUE TITLE
Allow grouping of sources

### ISSUE THREAD

**Issue by ghost** [xjsframework/xjs#27]
> Someone should really consider creating groupings, with a collapsible tree view so items could be put into logical groupings and save some space. Disabling a group of items rapidly from a grouped tree view would be pretty slick too. While you can accomplish this by creating different scenes the GUI gets fairly messy when you start inputing several items.
> ~ tkntobfrk

This was originally filed on #6

**Comment by hlevring** [comment]
This is already a highly prioritized feature request in our internal jira. Hopefully we will see this in version 2.7 before end of the year

**Comment by matthijskooijman** [comment]
Isn't grouping implemented in XBC already? I think you can also access groups from XJS, could this be closed?

**Comment by SML-MeSo** [comment]
Thanks for the heads up. Implemented in #261.
