### ISSUE TITLE
View itemID in xsplit gui

### ISSUE THREAD

**Issue by tkntobfrk** [xjsframework/xjs#29]
Would be handy to have the ability to find/see the item ID's in the gui while developing plugins. Maybe a property or advanced tab. e.g:  html, Color, layout, transition, properties/advanced.

**Comment by Matrim-Cauthon** [comment]
If we create a developer-only startup parameter for the above, the problem with an additional tab would be with plugins that do not use the tabbing system. We cannot insert a new tab into their HTML this way, not without possibly breaking their plugin layout.

However, we're exploring different possibilities to make development of plugins easier. At the moment we are considering a Developer Extension that could display much-needed information such as plugin IDs as you mentioned.

That idea is not final yet but I think we can schedule tackling this issue in one of our future milestones. In the meantime, if there are other pertinent bits of information that you think will be relevant to plugin development, please drop a note in this thread :thumbsup:

**Comment by Matrim-Cauthon** [comment]
Just to close this item --- if item ID is all you need, then you can create a very simple extension that updates its view based on the last clicked item. Simply make use of the ExtensionWindow and its ability to receive the [sources-list-select event](http://xjsframework.github.io/api.html#/window/ExtensionWindow).
