### ISSUE TITLE
Documentation for getDataFlow() has incorrect casing

### ISSUE THREAD

**Issue by matthijskooijman** [xjsframework/xjs#298]
The docs say:
https://github.com/xjsframework/xjs/blob/9bab38d255e76bd212f01d21863b980d9678300b/src/system/audio.ts#L118-L119

But in practice, I've seen devices return `Render` and `Capture`, so with a capitalized initial letter. Maybe these should be class-level constants in any case?

**Comment by SML-MeSo** [comment]
Yup, rechecked and the returned values, even on the core level, are indeed capitalized, will update.
