### ISSUE TITLE
HTMLItem set methods related to setBrowserJS and CustomCSS does not resolve HTMLItem instance

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjs#30]
The following methods has the possibility of not using the correct instance of `this`:

```
enableBrowserJS
setBrowserJS
enableCustomCSS
setCustomCSS
```

The reason behind this is due to the usage of `this` within a `function() {}` instead of using fat arrow functions (`() => {}`)

**Comment by Matrim-Cauthon** [comment]
Closed by 3e94169
