### ISSUE TITLE
Bug: Name of audio device not updated on AudioSource.setValue()

### ISSUE THREAD

**Issue by matthijskooijman** [xjsframework/xjs#300]
The name of an AudioSource seems to reflect the name of the audio device selected. However, when running setValue(), the name is not updated, which is inconsistent with e.g. MediaSource.setValue which *does* update the name.

I assume that the GUI does update the name when selecting a default device, but haven't been able to confirm that (having some issues with XBC crashing on this older PC, plus some weirdness wrt linked sources).

**Comment by SML-MeSo** [comment]
For fixing, will also recheck all the other source types and their intricacies with respect to changing sources

**Comment by SML-MeSo** [comment]
Upon checking, here are the source types where we need to specifically change the names:
- camera (needs additional checking for device name)
- audio (needs additional checking for device name)
- HTML (preferably, only if has no config, i.e. to consider HTML plugins which may change their name)
- flash (preferably, only if has no config, i.e. to consider legacy SWF plugins which may change their name)
- image
