### ISSUE TITLE
Issues with case sensitive matching

### ISSUE THREAD

**Issue by matthijskooijman** [xjsframework/xjs#301]
I noticed a number of places where case sensitive matching is problematic:
 - As reported in #295, setValue on MediaSource only allows lowercase extensions: https://github.com/xjsframework/xjs/blob/a1197da3015af103462a8d7ab4dff60c6b07e329/src/core/source/iplayback.ts#L644 (not that VIDEO_REGEX and AUDIO_REGEX are likely used in other places too).
 - Also reported mentioned in #295, sourceTypeResolve only treats lowercase extension as MediaSources: https://github.com/xjsframework/xjs/blob/a1197da3015af103462a8d7ab4dff60c6b07e329/src/util/sourcetyperesolve.ts#L35-L37. This also applies to itemTypeResolve. Note that there's also stream url matching, which also assumes lowercase (but I suspect RTMP:// also works in the GUI).
 - A new one I noticed today: sourceTypeResolve only treats uppercase GUIDs as AudioSource, but I've seen lowercase GUIDs as well (on one system, one input device produced a lowercase GUID and the other produced an uppercase GUID). I think case insensitive matching would make sense here as well. This also applies to itemTypeResolve.

**Comment by SML-MeSo** [comment]
For fixing, will also conduct a general recheck of all possible cases of case-sensitivity bugs :)
