### ISSUE TITLE
Allow plugin to request changing of source properties dialog title

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#31]
The title of the source properties dialog shows the name of the source selected (plugin name, or the custom name for the source if set by user). Any changes to the plugin name while source properties dialog is open is only reflected in the sources list, and not on the source properties dialog. Thus, a new method trigger that change without needing source properties dialog to close.

* Note that re-opening the source properties dialog will display the name of the source (as displayed in the sources list) regardless of what you set via this call.

**Comment by Matrim-Cauthon** [comment]
Hi @SML-MeSo please fix the documentation :)

**Comment by SML-MeSo** [comment]
done :)
