### ISSUE TITLE
Standardize naming of classes to be consistent with our public nomenclature

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#34]
We've undergone several iterations of the framework now in order to get to the point where we are able to very clearly and accurately represent the different elements of XSplit Broadcaster. However, we still retain the same naming from our very first attempts at creating the framework. These naming conventions may cause confusion if they do not match the terminology we use to communicate with users publicly.

For example, we use `Item` / `GameItem` / `HTMLItem` etc., for our different types of sources. The term *item* is not very clear in this regard. Also, we use the term Source Configuration Window to refer to what we publicly call *source properties dialog* (I also see us occasionally using *source properties window* for this.)

In line with our other efforts for consistency and standardization (#28, #17), I propose we change all `Item` / `GameItem` etc. references to `Source` / `GameSource` instead. I also propose we change the name `SourceConfigurationWindow` into `SourcePropertiesWindow` (`SourcePropertiesDialog` might also work, but I personally think that the words "source properties" are already clear enough, and we're already using "window" for the other corresponding classes: `SourcePluginWindow`, `ExtensionWindow`).

Do you think this is a good move, @SML-MeSo, @dcefram ?

**Comment by dcefram** [comment]
+1

**Comment by hlevring** [comment]
+2
