### ISSUE TITLE
Allow adding images and media items to stage

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#37]
(not sure if they should be separated but we need to implement both for 0.9.0 nonetheless)

**Comment by hlevring** [comment]
What do you refer to when you say media items? If you mean videos then it
makes sense to separate from images.

**Comment by Matrim-Cauthon** [comment]
Type detection for these items is already implemented, we just need to check if they use the same internal calls to add to the stage. Yes we've separated images from other media as they have different methods available. We're using "media" (term taken from bottom panel) to refer to both audio and video that have playback capabilities. We may still separate audio and video if necessary.
