### ISSUE TITLE
Item Layouts mixed up top/left

### ISSUE THREAD

**Issue by LtSquigs** [xjsframework/xjs#42]
Looks like this line of code has the top/left coordinates swapped:

https://github.com/xjsframework/xjs/blob/67ec232651c550a240b378921fa1fd27f4613857/src/core/item/ilayout.ts#L81

`fromCoordinates` has the order of "top, left, right, bottom", but thats being initialized with "left, top, right, bottom".

This makes the getPosition() function return bad rectangles.

**Comment by Matrim-Cauthon** [comment]
Noting a breaking change here --- {{Rectangle.fromCoordinates}} will now follow LTRB coordinate order. We'll stick with this one for all coordinate-related operations as XBC uses this order internally for positions / resolutions / etc.
