### ISSUE TITLE
Support for browserify bundler with babelify

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjs#46]
If you want to code using ES6, XJS framework would need you to switch your bundler from browserify to webpack since it won't work with browserify at all.

Forcing people to switch away from their preferred build process is obviously not a good thing, so we'll need to figure out a way to make XJS framework compatible with browserify (somewhat much more popular than webpack as of now) out of the box.

**Comment by dcefram** [comment]
Browserify is quite tricky than it should be. Currently it behaves abnormally when trying to compile es2015 modules located under node_modules folder. I filed a separate issue in babelify since it's weird that it would work if the project was under bower_components folder, but wouldn't work when under node_modules folder.

So the workaround that I think would work across the board (ie. getting xjs through npm or bower) is by modifying the ES5 bundled version of xjs framework to work with es2015. (That is, always add module.exports = _require('xjs'); to the end of the file).

The gulp task shall create an xjs-es2015.js file that would work for browserify-based projects. I shall commit it on a separate branch and reference it to this issue for you guys (@SML-MeSo and @Matrim-Cauthon ) to review.

**Comment by Matrim-Cauthon** [comment]
Please also check if there will be any necessary changes to our existing documentation / if there are new articles that need to be written accordingly.

**Comment by dcefram** [comment]
Yes, we'll need to modify the tutorial for developing plugins using es2015 to include an option of using a bundled version rather than the modular approach. Key differences is that the bundled version would work with browserify and webpack, whereas the modular version would work only on webpack (for now, until babelify supports it).

For the documentation/tutorial, I filed a separate issue on xjsframework.github.io's issue tracker (https://github.com/xjsframework/xjsframework.github.io/issues/10)
