### ISSUE TITLE
Improved handling of DLLs with respect to new DLL security scheme

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#49]
As of latest internal XBC build, we are now able to take advantage of DLL security, but this implies several changes in development style. Current programming patterns in our plugins that require DLLs are insufficient / will result in broken or inconsistent plugins, so ideally we should encapsulate required changes in the framework so everything will be easier.

Things to note for implementation:
- loading of DLLs should be handled. This needs asynchronous operations now so any `CallDllEx` calls need to wait until access is granted.
- we now need to distinguish between `CallDll` and `CallDllEx` calls
- enhancement: since revoking DLL grants does not fully work until the source is reloaded, the framework needs to automatically reload plugin on grant revocation. (An option to NOT reload can be specified)

@SML-MeSo @dcefram please comment on these requirements before we start implementation

**Comment by dcefram** [comment]
> loading of DLLs should be handled. This needs asynchronous operations now so any CallDllEx calls need to wait until access is granted.

We should also consider the scenario wherein the ``unsafe dll security`` is disabled on the advance tab. I believe ``UpdateLocalProperty`` wont be called if that is disabled.

**Comment by Matrim-Cauthon** [comment]
Additional insights from @SML-MeSo: might be good to have some event system, or at the very least distinguish when access is granted or revoked. Because developers want to call DLL functions when access is granted, but also sometimes they might want to display error messages when access is revoked.
