### ISSUE TITLE
stream start event

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#5]
Something that wasn't available in the old plugin system, but would be extremely useful, is to have an event emitted when a channel goes online or offline. Ideally the event would include the channel object for the stream.

If I understand the new Channel class correctly, currently the only way to tell if a stream is online is to poll `getActiveStreamChannels`.

As a simple example use case, I would like to make a timer that shows how long a stream has been active. At the moment, I have to continually poll to see if the stream is online and then `getStreamTime` to see how long, but if there was an event emitted when going online and offline, I could have the timer start and stop with the stream and avoid polling all together.

**Comment by SML-MeSo** [comment]
Hi! Adding certain helpful events such as these are definitely on our to-do list. Unfortunately, these needs some changes to be implemented in XSplit Broadcaster itself in order to be supported.

Will check on this with the core developers and hopefully will be included in the next XBC developer build so we can add it into the framework

**Comment by Matrim-Cauthon** [comment]
@SML-MeSo can we confirm if we already have the necessary changes in XBC to implement this? If so, we can schedule this in the next milestone.

**Comment by dcefram** [comment]
This is similar to #88. This should be available on the latest 'internal' build. We might opt to release one of the internal build as a developer build later on when we're done with #85

**Comment by hlevring** [comment]
I suggest we have a quick discussion on this one..

**Comment by dcefram** [comment]
Looks good to me, how about on your end @virn?
