### ISSUE TITLE
Add hardware encoder detection for CameraClass

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjs#52]
This method would be really useful when filtering Cameras and Capture cards.

Sometimes a plugin will only want to manipulate a camera, and not capture cards. This method might help doing such task.

**Comment by dcefram** [comment]
Or, I think it'll be a lot better if the framework can somehow tell the difference between a capture card and a camera

**Comment by xjsframework** [comment]
As of Milestone 1.0, hardware encoder checking is already included. However, this method automatically fails (defaults to false) if camera source is not active. For this, we added another method, isActive and improved the current isHardwareEncoder check to reject if source is not present and only resolve to false for non-hardware encoders.

**Comment by SML-MeSo** [comment]
As of Milestone 1.0, hardware encoder checking is already included. However, this method automatically fails (defaults to false) if camera source is not active. For this, we added another method, isActive and improved the current isHardwareEncoder check to reject if source is not present and only resolve to false for non-hardware encoders.
