### ISSUE TITLE
Transition class doesn't play well with custom transitions

### ISSUE THREAD

**Issue by farpenoodle** [xjsframework/xjs#55]
Currently will return Transition.NONE when set to a custom transition.

**Comment by SML-MeSo** [comment]
upon looking, two changes need to be made, one is for App.getTransition to properly return a new transition class, and two, is for a method to know all available transitions (even custom) for use in App.setTransition. First one is already done, but the second needs some changes on XBC

**Comment by SML-MeSo** [comment]
Also, since both source and extension shares the transition class, it is imperative to document and reflect in the framework that only the base transitions will work for source, and not stingers
