### ISSUE TITLE
save active extensions with presentation

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#6]
When an extension is integral to a particular presentation, it would be nice if it were possible to save the current active extensions (along with their window size/position) as part of a presentation so that they open automatically when the presentation opens. In the current system, if there is an extension that is used all the time, you still have to reopen it each time you open xsplit. 

As a related feature, it would be useful to be able to activate and possibly manipulate an extension from another plugin or extension.

**Comment by dcefram** [comment]
Hi! As of now, XSplit broadcaster does have methods for saving extension plugin's properties (configs, etc.) but we did not yet implement that on our framework.

What XSplit broadcaster does not yet provide though is the ability to auto open an extension plugin if the extension's properties was saved on the presentation file. We will forward the feasibility of that feature request with the other devs responsible with the actual XSplit Broadcaster client, but in any case, it would take longer to implement (requiring an update on the actual XSplit Broadcaster software).

As for now, we will implement to the framework what is already available on the current XSplit software, and that is the ability to save extension plugins' configuration/properties to the presentation file.

**Comment by tkntobfrk** [comment]
This feature would be nice, another feature thats not directly tied to the api is the scene items window. Someone should really consider creating groupings, with a collapsible tree view so items could be put into logical groupings and save some space. Disabling a group of items rapidly from a grouped tree view would be pretty slick too.  While you can accomplish this by creating different scenes the GUI gets fairly messy when you start inputing several items.

**Comment by hlevring** [comment]
Grouping is something we have wanted to add for a while. Will do our best to get it prioritized in one of the upcoming releases.

**Comment by dcefram** [comment]
Just to make this task clear, we will implement saving of presentation data/configuration on 0.8.0

Other requests:
- capability of informing XSplit what extension plugins should open up on startup
- the ability to manipulate extension plugins through other extension plugins or source plugins
- grouping sources

These requests would need an update on the client itself, and the first two are still subject for discussion with the people responsible of implementing it. We will file it as a separate issue to track the status of each feature request.

**Comment by Matrim-Cauthon** [comment]
Saving extension plugins' configuration is now accomplished by b2fa733.
