### ISSUE TITLE
Add additional methods to the ScreenSource class

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#62]
- show mouse
- show mouse clicks
- capture layered windows
- optimize window capture

**Comment by Matrim-Cauthon** [comment]
@virn the get* methods return the source instead of the intended values. Not sure why TypeScript didn't detect the type inconsistencies.

There also seems to be a stray string (line 341) :D

**Comment by Matrim-Cauthon** [comment]
See f8f5ac2 for implementation
