### ISSUE TITLE
Deprecate isSourceConfig environment function

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#64]
This was overlooked for v1 update which included consistency in naming. Let's duplicate functionality into isSourceProps instead, and mark isSourceConfig as deprecated for now.

Initially assigning to @dcefram as this issue primarily deals with how we should display/generate code for deprecated functions

**Comment by dcefram** [comment]
Here's some example of docs with deprecated functions

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape
https://facebook.github.io/react/docs/component-api.html#setprops
https://code.angularjs.org/1.3.0-beta.11/docs/api/ng/service/$compile#-replace-deprecated-will-be-removed-in-next-major-release-

Is it just fine to simply add some sort of text appended to the method name in our docs?

Example:
**static isSourceConfig (NOTICE: For Deprecation)**

or add another row, probably styled as a quote.

**static isSourceConfig**

> Notice: For Depracation
use isSourceProps instead

**Comment by Matrim-Cauthon** [comment]
Perhaps it's better to have additional text for any deprecated functions. At the very least, we can link them to what function should replace the deprecated one; for more complex issues, we can give a more detailed explanation.

**Comment by dcefram** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/687325/13244253/c3ba673c-da3f-11e5-91c1-67b8d5a66b69.PNG)

Here's a screenshot of what it would look like. Not sure if this would be enough though.
