### ISSUE TITLE
Compatibility issue with webpack ts-loader

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjs#68]
Tutorial link: http://xjsframework.github.io/tutorials.html#/es6

The steps on the tutorial (webpack tutorial) will not work with the latest version of [ts-loader](https://github.com/TypeStrong/ts-loader). I cannot remember which version of ts-loader works, but currently, it does not.

My initial investigation points to our [tsconfig.json](https://github.com/xjsframework/xjs/blob/master/tsconfig.json) as the cause of this issue. ts-loader seems to be reading tsconfig.js instead of [package.json's main](https://github.com/xjsframework/xjs/blob/master/package.json#L8) value (the behavior before is that ts-loader ignores tsconfig.json, and compiles the file that is declared on package.json's main value)

My suggestion is to just remove `compileOnSave` and `filesGlob`. `files` attribute should only include one file, and that is `./src/index.ts` since `index.ts` imports all the needed files.

**Comment by Matrim-Cauthon** [comment]
Whatever our solution may be, we should probably set our dependencies in package.json to specific versions only instead of version ranges while we're working on this issue, as well.

**Comment by dcefram** [comment]
XJS Framework does not use ts-loader, but the project generated by our generator-xjs installs the latest version [programmatically](https://github.com/xjsframework/generator-xjs/blob/master/generators/webpack/index.js#L101).

Should we update our generator and specify to only fetch the `v0.6.1` tag of ts-loader? (just checked the saved initial version of ts-loader on my package.json, which worked before I updated my npm modules)

**Comment by Matrim-Cauthon** [comment]
Maybe we can do that as a stopgap fix, and also check what updates were in the newer versions so that we can determine whether we want to and how to update the relevant configurations (because eventually we'll probably need to move forward).

**Comment by dcefram** [comment]
> what updates were in the newer versions so that we can determine whether we want to and how to update the relevant configurations

The only relevant difference between the older version of ts-loader and the latest version is that the older version does not support tsconfig.json, while the latest version supports tsconfig.json. 

The reason why it wasn't supported before is since tsconfig.json was only introduced in version 1.5 of TypeScript. As for our tsconfig file, the last time we updated that was 6 months ago, and was auto generated by atom editor. With that said, I think we can safely go ahead and update our tsconfig.json.
