### ISSUE TITLE
scene-load event for source plugin

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#70]
Extensions can register for the `scene-load` event to do things when the scene changes, but is there anyway for a regular source plugin in the scene to be notified when its scene is switched to? If `Keep Source in Memory` is *unchecked*, the source will reload with the scene, of course, but if you are using `Keep Source in Memory`, I don't see a way for a source to tell when it is active (as opposed to rendering in the background). Can sources also register for the `scene-load` event or is there another way to detect when the user has switched to a source's scene?

**Comment by dcefram** [comment]
I did a quick look and found out that it's supported in XSplit. However, we missed this part in our framework, and we should add this on our next version of the framework.

If you really need it right now, you can make use of `window.OnSceneLoad`. Ex:

```javascript
window.OnSceneLoad = function() {...}
```

In the next version of xjs, we would like to have something like:
```javascript
xjs.Item.getCurrentSource().then(function(item) {
  item.on('scene-load', function() { ... });
});
```

I'll add this to our 1.2.0 milestone. Thanks for adding this issue :)

**Comment by Matrim-Cauthon** [comment]
Additional clarification for `window.OnSceneLoad` above:

Unlike extensions, sources may only detect their own scene being loaded. An additional caveat is that this also triggers when the scene is loaded in the preview (such as when you hover over the Scene's button in XBC.)

Hopefully that is not an issue for your use case.

**Comment by paul-lrr** [comment]
Is there any way to detect if the current scene is a preview or a "real" scene? The old API had the `GetViewId()` function that returned 0 if called in a regular scene or 1 if called from a preview scene.

**Comment by Matrim-Cauthon** [comment]
We've checked and we have the complete set of steps (found in #72). It requires simply checking a source's viewID property, so there shouldn't be too much complexity in the implementation.

For now I'm putting this in 1.2.0 release, slated for February 29.
