### ISSUE TITLE
Prevent Props window on right click

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#71]
I have a plugin that displays a number which the user can increment and decrement by clicking directly on it in the scene window (they don't have to go into the props). Ideally it would be left click to increment and right click to decrement. Capturing the left or middle click event is no problem, but when I right click on the source, it automatically opens the props window. `Event.preventDefault`, returning false or other normal ways to prevent default click events doesn't seem to stop it, I assume because showing the props window is low level XBC function and not affected by xjs. Is there any way to override this default action and allow the source plugin to register the right click? This will make it so the user has to right click on the source in the source list instead of the scene window to get the props window, but that is fine for this situation.

**Comment by dcefram** [comment]
Preventing props window from showing up is currently not possible in XBC. We could request that change to our core dev team, but that 'might' take time, depending on their schedule.

However, if your main objective is to allow the source plugin to register right click events, that is already possible in our current version of XBC (2.7). We were not able to add that to our framework though.

I'll do this and commit it to a branch and link it here for you to check it out. Give me a moment :)

**Comment by dcefram** [comment]
As discussed with @SML-MeSo, we'll move the methods to HtmlSource and FlashSource classes.
