### ISSUE TITLE
Append license file to dist files

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjs#75]
We should append the license file to xjs.js, xjs.min.js, and xjs-es2015.js

**Comment by Matrim-Cauthon** [comment]
@dcefram is there a valid reason why this is not part of the default build task?

**Comment by dcefram** [comment]
None really, just aesthetics.

Compare:
```javascript
/**
 * XSplit JS Framework
 * version: 1.2.0
 **/
/**
 * LICENSE here
 **/
```

vs

```javascript
/**
 * XSplit JS Framework
 * version: 1.2.0
 *
 * LICENSE here
 **/
```

**Comment by Matrim-Cauthon** [comment]
Item is ready for release. @SML-MeSo @virn please take note that we now need to run `gulp version major|minor|patch` when pushing out any new release. The default `gulp` task does not add any license header.
