### ISSUE TITLE
Add additional window handing for extension window

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjs#76]
XBC already supports setting the border types of extension windows, so I think we should add this feature to our framework.

Aside from that, it'll be good to also have methods for closing/minimize/maximize/restore the window. Also, it'll be good to have a method that would allow you to move the extension plugin window on drag.

**Comment by Matrim-Cauthon** [comment]
The proper flags are set, but I have two concerns:

1. Disabling the Close button doesn't have any visual changes to the button whatsoever; disabling simply means that clicking the button doesn't do anything.
2. Setting any border options seems to require the user to drag the window first before the changes are applied. (Side-note: re-enabling "caption" after disabling it seems to remove the original title. But perhaps this is an edge case that doesn't need to be handled, as the border options for an extensions probably don't need to change all the time.)

@dcefram @virn I'm not sure if above is acceptable behavior. Should we mark this item as ready for release, and file new items for fixes on the application level?

**Comment by virn** [comment]
For item 2:
I was also able to notice this on my end, but upon testing on @SML-MeSo machine, the changes happened immediately. This may due to refresh rate?

**Comment by dcefram** [comment]
I think we can still mark this item as ready for release, we just have to make sure that we list those issues as known issues for the current public release.

**Comment by Matrim-Cauthon** [comment]
Main implementation in commit 197796f
