### ISSUE TITLE
XjsEx.dll - Unzip support

### ISSUE THREAD

**Issue by pointnet** [xjsframework/xjs#79]
Could you guys support unzipping through XjsEx.dll ?

**Comment by Matrim-Cauthon** [comment]
Hi, I've filed this as a feature request to our core team.

Unfortunately, while we will strive to provide support for the framework, the DLLs are another matter; I cannot give any guarantees for this request. :(

If it helps, I can point you to the direction of our [DLL creation tutorial](http://xjsframework.github.io/assets/WritingcustomXSplitscriptDLLsinC.pdf). This method will allow you to proceed with your development much quicker and will help you update faster should your needs change.

For now I'll close this issue and mark it as wontfix. I'll just reopen this issue if we get positive updates on our end.

**Comment by Matrim-Cauthon** [comment]
Reopening this as it appears that we will be supplying relevant calls for this.

**Comment by virn** [comment]
Added the documentation for the website on [xjsframework.github.io/xjs-79](https://github.com/xjsframework/xjsframework.github.io/tree/xjs-79)

**Comment by Matrim-Cauthon** [comment]
Marking as ready for release, but this is essentially just a documentation update. We will have to release a new XBC developer build for 1.4 for this feature.
