### ISSUE TITLE
migrating from previous xui framework

### ISSUE THREAD

**Issue by tkntobfrk** [xjsframework/xjs#8]
I'm upgrading to this newer framework, but its not clear to me how to port what I was doing

In the previous framework, I was updating rtmp/images items with

var slot = internal.Item.attach(id, 0);
internal.Item.set('prop:item', decodeURIComponent(itemString), slot);

It's not clear what method I would use in the new framework to accomplish the same task. I'm guessing there is a way to update   "_xmlparams":  ?

**Comment by dcefram** [comment]
We could actually help you migrate your code if you need help. As for the code above, you could get the same results using this:

```
var xjs = require('xjs');
xjs.ready().then(xjs.Item.getCurrentSource)
  .then(function(curItem) {
    // your logic for the itemString here
    curItem.setValue(decodeURIComponent(itemString));
  });
```

We do not expose the internal class on this framework anymore, but I believe that what we have exposed on the item class is enough for doing most of the things that you would do with an item source.

I'm not totally sure about the 'xmlparams' that you're talkinf about, it might help if you send a sample code of what you want to migrate :)

**Comment by tkntobfrk** [comment]
I just did a dump of the all items and noticed _xmlparams

 {
    "_name": "RTMP Stream",
    "_cname": "",
    "_id": "{EB064B54-6659-4615-91C0-24068710AE08}",
    "_sceneID": 0,
    "_value": "",
    "_keepLoaded": "0",
    "_type": 6,
    "_xmlparams": {
      "tag": "item",
      "selfclosing": true,
      "type": "6",
      "item": "C:\\Users\\Bruce\\AppData\\Local\\SplitMediaLabs\\XSplit\\tkntobfrk@gmail.com\\SwfPlugins2.0\\LiveStream.swf*&lt;config&gt;&lt;params rtmp=\"rtmp:\/\/s3057ohquvmmjp.cloudfront.net\/cfx\/st\/\" stream=\"mp4:videos\/juiryproject\/no_video.mp4\" smoothing=\"true\" buffer=\"6\"\/&gt;&lt;\/config&gt;",
      "itemaudio": "",
      "name": "RTMP Stream",
      "cname": "",
      "pos_left": "0.171094",
      "pos_top": "0.055556",
      "pos_right": "0.814844",
      "pos_bottom": "0.694444",
      "crop_left": "0.000000",
      "crop_top": "0.000000",
      "crop_right": "0.000000",
      "crop_bottom": "0.000000",
      "pixalign": "0",
      "zorder": "17",
      "volume": "100",
      "mute": "0",
      "sounddev": "0",
      "lockmove": "1",
      "keep_ar": "1",
      "fdeinterlace": "0",
      "mipmaps": "0",
      "autoresdet": "1",
      "visible": "1",
      "keeploaded": "0",
      "alpha": "216",
      "border": "0",
      "cc_pin": "0",
      "cc_brightness": "0",
      "cc_contrast": "0",
      "cc_hue": "0",
      "cc_saturation": "0",
      "cc_dynamicrange": "0",
      "key_pin": "0",
      "key_antialiasing": "2",
      "key_chromakey": "0",
      "key_chromakeytype": "2",
      "key_chromahue": "0",
      "key_chromarang": "25",
      "key_chromaranga": "0",
      "key_chromabr": "25",
      "key_chromasat": "25",
      "key_colorrgb": "0",
      "key_colorrang": "25",
      "key_colorranga": "0",
      "key_chromargbkeyprimary": "1",
      "key_chromargbkeythresh": "50",
      "key_chromargbkeybalance": "0",
      "key_smartcamenable": "0",
      "key_smartcamconfig": "",
      "rotate_x": "0",
      "rotate_y": "0",
      "rotate_z": "0",
      "rotate_canvas": "0",
      "offset_x": "0.000000",
      "offset_y": "0.000000",
      "transitionid": "",
      "transitiontime": "300",
      "edgeeffectid": "",
      "edgeeffectcfg": "",
      "syncid0": "2225581641",
      "syncid1": "1215595752",
      "syncid2": "530523015",
      "syncid3": "3017514703",
      "id": "{EB064B54-6659-4615-91C0-24068710AE08}",
      "StreamDelay": "0",
      "AudioDelay": "0",
      "AudioGainEnable": "0",
      "AudioGain": "5",
      "AudioGainLatency": "1000",
      "LiveClockSync": "0",
      "InPoint": "0",
      "OutPoint": "0",
      "CuePoints": "",
      "FilePlaylist": "",
      "OpWhenFinished": "0",
      "StartOnLoad": "1",
      "RememberPosition": "1",
      "LastPosition": "0",
      "LastRunState": "-1",
      "ShowPosition": "0",
      "ScrCapMethod": "3",
      "ScrCapLayered": "0",
      "ScrCapOptCapture": "0",
      "ScrCapOptCapture1": "1",
      "ScrCapIntResize": "0",
      "ScrCapShowMouse": "1",
      "ScrCapShowClicks": "1",
      "ScrCapTrackWindowTitle": "0",
      "GameCapShowMouse": "0",
      "GameCapSurfSharing": "0",
      "GameCapAlpha": "0",
      "GameCapPlSmooth": "1",
      "GameCapPlSmoothness": "1.000000",
      "GameCapTrackActive": "0",
      "GameCapTrackActiveFullscreen": "1",
      "GameCapHideInactive": "0",
      "BrowserJs": "",
      "BrowserSizeX": "0",
      "BrowserSizeY": "0",
      "BrowserTransparent": "1",
      "BrowserRightClick": "0",
      "BrowserCookiePath": "",
      "BrowserCookieFlags": "0",
      "Browser60fps": "0",
      "SwfWrapper": "0",
      "DllGrant": "",
      "custom": "",
      "value": "",
      "sceneID": 0
    }
  },

**Comment by tkntobfrk** [comment]
As for the previous code that runs most of what I swap in/out. I used code similar to the below for swapping out rtmp stream mp4/mp3 sources, and some similar logic for pictures/images. Looks like  a lot of this previous logic can be avoided with the getCustomName. New framework looking so much easier to handle. will have a better look tomorrow.

   var rtmpItem;
            var id;
             xui.core.View.MAIN.getScene(0).then(function(scene) {
                return scene.getItems();
            }).then(function(items) {
                var _getName = function(item) {
                    return new Promise(function(resolve, reject) {
                        item.getName().then(function(name) {
                            // Assuming that we did not update the prop:name of the RTMP Stream item source
                            if (name === 'RTMP Stream') {
                                resolve(item);
                            } else {
                                resolve(false);
                            }
                        });
                    });
                };

                var promises = [];

                for (var i in items) {
                    promises.push(_getName(items[i]));
                }

                return Promise.all(promises);
            }).then(function(items) {
                for (var i in items) {
                    if (items[i]) {
                        rtmpItem = items[i];
                    }
                }

                // Get the value of the rtmp stream item source (prop:item)
                return rtmpItem.getID();
            }).then(function(_id) {
                var slot = internal.Item.attach(_id, 0);
                id = _id;
                return internal.Item.get('prop:item', slot);
            }).then(function(itemString) {

              var itemParts = itemString.split(' ');
                if (itemParts[1] !== undefined) {

                    itemParts[1] = 'rtmp="rtmp://' + itemData.mediaRTMPCDN + 'cfx/st/"'
                    itemParts[2] = 'stream="mp4:' + itemData.mediaName + '"'
                }

                itemString = itemParts.join(' ');

                var slot = internal.Item.attach(id, 0);
                internal.Item.set('prop:item', decodeURIComponent(itemString), slot);

            });

**Comment by dcefram** [comment]
Hi, I tried migrating your code. Please check this diff:

https://gist.github.com/dcefram/3edd68a5fdbde5ae43e2/revisions?diff=split

**Comment by tkntobfrk** [comment]
This works just like the old code, I had some variations on the code and it seems to work there too.
