### ISSUE TITLE
Compatibility for XBC Global sources build

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#85]
We will need to perform changes on the framework to be compatible with the new global sources builds of XBC.

Here are the points we concluded on in our meeting:
- within the Source Props and Extension contexts, no change to initialization process is necessary
- getCurrentSource does not make any sense now that we're going to be dealing with individual video items, so we will create getCurrentItem instead
- most methods will now be delegated to the "video item" instead of a source (codewise for the framework, not much difference as the implementations are already in the separate interfaces)
- developers will not be dealing with sources directly any more, so we will use the video items instead (revert to the usage of HTMLItem instead of HTMLSource)

This Github issue covers two goals:
- fix the bugs and incompatibilities caused by the changes in XBC core
- apply a temporary compatibility layer: (two points: [1] deprecate the "Source" classes and use "Item" classes instead, but allow them both to have the same feature set, and [2] deprecate "getCurrentSource" and rewrite it to return the first instance of a video item in the item list, as a stopgap measure for pre-XBC 2.8 plugins)

@dcefram please collaborate with @virn on this issue. I'll link other related issues here as well.

**Comment by Matrim-Cauthon** [comment]
Additional investigation needed for "source events" in 2.7. How will they work in the new builds? We'll need to create some level of compatibility probably.

**Comment by dcefram** [comment]
Here's a task list for us to monitor what's still missing.

- [x] Create Item Class (Source class should extend Item Class)
- [x] Implement `Item.getItemList`
- [x] Update `Item.getCurrentSource`. Use `Item.getItemList` instead of `prop:item`
- [x] Set Item ID locking only in Source props environemnt
- [x] Update internal item class to handle the new slots (if souce plugin environment)
- [ ] Update comments/docs

_Not yet fully tested_

**Comment by dcefram** [comment]
We identified additional changes needed for this to prevent us from a major version up. Updated the todo list above.

**Comment by Matrim-Cauthon** [comment]
I think we will also need to force the deprecated methods to output warnings when they are invoked.

**Comment by dcefram** [comment]
agreed!

**Comment by Matrim-Cauthon** [comment]
Merged develop into #85 in commit 69c82d1, and reverted wrong merges in commit 4de9c10

Some notes that we'll need to go over:
- There are probably new features from source/ieffects that need to be handled as well. (#59) (For example, check MaskEffect in index.ts)
- I think we can do better with the comments for deprecated source classes. We don't need to specify the inheritance hierarchy (remove the entire section about x extends y, just clarify in first paragraph that the methods in the Item classes are shared)
- There seems to be duplicate version-related code in internal/item and internal/init. Let's fix this.
- Please check the latest version of internal/init -- I'm not sure I merged it perfectly.

These are just the initial issues from the review, but @dcefram also mentioned a possible bug when dealing with the source props window for global sources in the preview editor. (related to #77)

**Comment by Matrim-Cauthon** [comment]
Passing back to @dcefram -- we'll need to do more work on the test cases here, I think many things aren't working as they should.

It seems that the lack of a 2.8 check is causing Item.get/set to fail, thus causing all specs for item subclasses to fail.

I'll give this another look after another pass at your end :eyes:

**Comment by dcefram** [comment]
bae259bab1f61bb22263786ac949feae8ba66482

This commit will make all test cases to work. All we did is to mock the `navigator.appVersion`'s value.

**Comment by virn** [comment]
Found out that we are still haven't changed `setSourceOrder` into `setItemOrder`. For now, we only need to create the `setItemOrder` function.
