### ISSUE TITLE
Control Local recording

### ISSUE THREAD

**Issue by pointnet** [xjsframework/xjs#88]
Adding support for local recording options, start, stop, pause.
Use case: automatic youtube video upload during tournaments.

**Comment by dcefram** [comment]
This feature will require changes in XSplit Broadcaster itself. The good news though is that this was already planned for the next XSplit Broadcaster release.

We'll add that feature to the framework probably slated for 1.4.0 release (? @Matrim-Cauthon ), and you'll be able to check it out once we release a new version of the developer's build.

**Comment by Matrim-Cauthon** [comment]
Please note that we're putting this issue on hold for now, until we can resolve certain issues with the XBC. (@meso @dcefram this involves possible movement of CallHost in the backend)

But #5 is just for the actual stream start/stop events so I think we can put that in the next release.

**Comment by Matrim-Cauthon** [comment]
Assigned to xjs@1.6.0 but we will need to discuss a number of implementation details under the hood first, then we can decide how/when to release a stream/recording control feature.

**Comment by Matrim-Cauthon** [comment]
Removing on-hold label; we will be implementing this through internal feature (XBC-5023).

I'll keep the target milestone as it is; this won't be able to fit into 1.5.0.

**Comment by virn** [comment]
Closed on f310a02
