### ISSUE TITLE
toXML does not make use of _xmlparams, thus rendering multiple private variables useless

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjs#89]
There is no huge bug with this issue, it's just that we have a couple private variables not being used anywhere that makes sense. (I'll be linking issue-86 branch, since that's the latest)

`_xmlparams` value: https://github.com/xjsframework/xjs/blob/issue-86/src/core/items/item.ts#L100
`toXML` method: https://github.com/xjsframework/xjs/blob/issue-86/src/core/items/item.ts#L539

The problem here is that [Line 91 ~ Line 98](https://github.com/xjsframework/xjs/blob/issue-86/src/core/items/item.ts#L91~L98) has no use if `this._xmlparams` is not used (aside from `this._id`, `this._sceneId` and `this._name`)

**What should be done:**

**Option 1 (recommended)** - Based from what @Matrim-Cauthon said, the initial logic here is that this._xmlparams SHOULD be used by `toXML` method. So with that said, we should update `toXML` method to:

```typescript
  toXML(): XML {
    var item: JXON = new JXON();

    for (let prop in this._xmlparams) {
      let _prop = prop === 'value' ? 'item' : prop;
      item[_prop] = this._xmlparams[prop];
    }
    item['tag'] = 'item';
    item['selfclosing'] = true;

    return XML.parseJSON(item);
  }
```

**Option 2** - Just remove those dead codes and leave `toXML` as is.

**Comment by Matrim-Cauthon** [comment]
We need to do option 1 to still allow toXML to be performed while preserving all item properties.

This will be useful in cases where we need the actual XML because a specific action is not yet available through the framework (i.e., copying and pasting items.)

Adding this to 1.4.0 release (we will need this asap), and assigning to @dcefram

**Comment by dcefram** [comment]
ref: 1af98d7974deb2613865a725f8b5cd49ee173455
