### ISSUE TITLE
Xsplit extensions examples

### ISSUE THREAD

**Issue by schneider82** [xjsframework/xjs#90]
Do you have some extension example. I would like to use the webserver I have already created for the content on the system to also change scenes and do a few other things plugins aren't allowed. I haven't created a plugin as yet simply using the HTML plugin. It would be great to have a walk through of the process of creating the extensions. Is this possible?

**Comment by dcefram** [comment]
We do have a sample extension plugin that is open sourced: https://github.com/xjsframework/scene-rotator.

If you're planning to create one from scratch, I suggest that you use our yeoman based generator to scaffold an extension plugin for you. ([Instructions](http://xjsframework.github.io/quickstart.html#yeoman))

Other info: [How to use extension plugins](http://xjsframework.github.io/tutorials.html#/extensions)

Try digging up with the codes, or play around with the generated project. Just comment on this issue if you got any other question while working on your plugin (or you can hit us up on [gitter chat](https://gitter.im/xjsframework/xjs)).

**Comment by Matrim-Cauthon** [comment]
Closing this issue. Please create a new issue if you have any more concerns with the framework. Thanks!
