### ISSUE TITLE
Event when a source becomes visible

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#92]
Is there an event that fires when a source becomes visible (or has been hidden)? Theoretically, I guess it would be possible by checking the source's `isVisible` property when the `SetVolume()` event fires (since that event is sent when the source is shown/hidden), but obviously that is a pretty hacky solution :smile: 

My particular use case is making a video file start playing when it becomes visible. Xsplit's built in video source can start a video when the scene loads, but doesn't seem to be able to wait until a video is shown before playing (If the video is hidden when a scene loads, it will still start playing in the background)

**Comment by Matrim-Cauthon** [comment]
Yeah, that would be a very hacky solution, and might change in the future :) For many global level calls such as `SetVolume` or `SourcesListHighlight`, we either stub it out to suppress errors (for the ones not handled yet) or wrap them through event emitters (`SourcesListHighlight` is now an event emitted by the only window that can receive that call, which is the `ExtensionWindow`.)

At the moment I think you can go with your solution, but we will definitely explore the feasibility of events fired for any item property change. At the very least, we'll need changes in XSplit itself to accommodate such a feature.

**Comment by SML-MeSo** [comment]
Closing this item as the solution would be a more general one, which is to resolved in the earlier referenced issue, #104
