### ISSUE TITLE
sources-list-select event

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#94]
I am interested in having an extension that affects the currently selected source in the source list. From what I can tell, there is no way to just get the currently selected source, but I figured it would work to use the `sources-list-select` event to track the last selected source. However, it appears that `sources-list-select` only fires when a source is selected *in the scene* not in the source list. That means that if a source is hidden or behind something, there is no way to fire the event. `sources-list-highlight` *does* work on both the scene and the source list, but having it tied to a mouseover makes it tricky to ensure the source you want is being registered.

Is there a reason that `sources-list-select` doesn't work in the actual source list? Given the name of the event, it seems odd. Alternatively, is there another way to either get the currently selected source in the source list or track when a source is selected from the list?

**Comment by SML-MeSo** [comment]
Confirmed the above behavior as a bug on the latest public release (XBC 2.7). We can't seem to find any alternative for this one, but we also confirmed that this is already fixed for the next public XBC release (XBC 2.8) which will be coming in the next few weeks. We'll try to update once an advance developer build is cleared for release or at the very least, once it is in public beta so you can proceed. Keeping this issue open until then.

**Comment by Matrim-Cauthon** [comment]
@SML-MeSo I'll mark this as 1.4.0 since it will be synced to the next XSplit release. Let's retest this issue with latest internal XBC builds when we release 1.4.
