### ISSUE TITLE
Apply name change to all items sharing the same source

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#95]
For global sources, calling setName only changes the name for the currently attached item, and is not mirrored to other items sharing the same source since name is included in the rendering properties. You'll then need to iterate over the globally connected items and individually call setName on them if ever changes in your plugin source needs to be reflected in their plugin names. The XBC text source and most of the XBC chat viewer plugins exhibit this behavior. We really can't find a use case for the individual setting, so putting this behavior as default (unless proven otherwise).

**Comment by dcefram** [comment]
Is this for review? I'm seeing the `review` label, but I can't seem to find the corresponding branch :P

**Comment by SML-MeSo** [comment]
My aplogies, failed to push the commit. Should be okay by now.
