### ISSUE TITLE
Bug: Maximum number of Scenes

### ISSUE THREAD

**Issue by marloeleven** [xjsframework/xjs#96]
receiving an Error when scenes are more than 12. If possible, it would be better if there is a method to fetch the actual number of scenes availble.

Since XBC 2.8 would be supporting variable number of scenes, the framework should also reflect that as opposed to hard-coded into 12 for XBC 2.7

**Comment by dcefram** [comment]
I think we also need to handle instances that the user loaded a .bpres file with only one scene.

**Comment by SML-MeSo** [comment]
Scene class methods verified working in the same behavior as the XBC version from which it is loaded whether it be XBC 2.7 or 2.8
