### ISSUE TITLE
Feature request: Emitter for Scene delete

### ISSUE THREAD

**Issue by marloeleven** [xjsframework/xjs#98]
please add an emitter for scene delete. Also for when scenes are added

**Comment by dcefram** [comment]
Filed internally in XBCPLUGINS-453. Already available in the current version of XSplit, we'll have to include this on the next version of XJS ;)

**Comment by nelson-temporal** [comment]
Added scene emitter for delete and add
     scene deletion event : 'scene-deleted' 
     scene added event : 'scene-added'

These would always return scene index.
